import Providers from '@/app/providers';
import { AuthGuard } from '@/components/auth-guard';
import { AuthProvider } from '@/context/AuthContext';
import Banner from '@/modules/home/banner';
import type { Metadata } from 'next';
import { Mulish } from 'next/font/google';
import React from 'react';

import '../globals.css';

const mulish = Mulish({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Download',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <Providers>
          <AuthProvider>{children}</AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
